In [30]:
import pandas as pd
import numpy as np


In [63]:
# Loding the data set
data=pd.read_csv('diabetes.csv')
data


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [64]:
data.shape

(768, 9)

In [65]:
#Splitting the dataset into training and test samples

from sklearn.model_selection import train_test_split
training_set, test_set = train_test_split(data, test_size = 0.2, random_state = 1)

In [66]:
#Classifying the predictors and target

X_train = training_set.iloc[:,0:2].values
Y_train = training_set.iloc[:,2].values
X_test = test_set.iloc[:,0:2].values
Y_test = test_set.iloc[:,2].values

In [67]:
#Initializing Support Vector Machine and fitting the training data

from sklearn.svm import SVC
classifier = SVC(kernel='rbf',gamma=0.6, random_state = 1)
classifier.fit(X_train,Y_train)

SVC(gamma=0.6, random_state=1)

In [68]:
#Predicting the classes for test set

Y_pred = classifier.predict(X_test)

In [69]:
#Attaching the predictions to test set for comparing

test_set["BMI"] = Y_pred
test_set

<ipython-input-69-c61f497785b6>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_set["BMI"] = Y_pred


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
285            7      136             74             26      135   90   
101            1      151             60              0        0   90   
581            6      109             60             27        0   80   
352            3       61             82             28        0   70   
726            1      116             78             29      180   70   
..           ...      ...            ...            ...      ...  ...   
563            6       99             60             19       54   70   
318            3      115             66             39      140   64   
154            8      188             78              0        0   70   
684            5      136             82              0        0   84   
643            4       90              0              0        0   70   

     DiabetesPedigreeFunction  Age  Outcome  
285                     0.647   51        0  
101                     0.179   22        0  
581                     0.206   27        0  
352                     0.243   46        0  
726                     0.496   25        0  
..                        ...  ...      ...  
563                     0.497   32        0  
318                     0.150   28        0  
154                     0.137   43        1  
684                     0.640   69        0  
643                     0.610   31        0  

[154 rows x 9 columns]

In [70]:
#8 predictions have gone wrong
from sklearn.metrics import confusion_matrix
from sklearn import metrics
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
print(metrics.classification_report(Y_test,Y_pred))
accuracy = float(cm.diagonal().sum())/len(Y_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         6
          46       0.00      0.00      0.00         1
          48       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         0
          52       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         1
          55       0.00      0.00      0.00         2
          56       0.00      0.00      0.00         2
          58       0.00      0.00      0.00         5
          60       0.20      0.09      0.13        11
          62       0.00      0.00      0.00         3
          64       0.00      0.00      0.00         9
          65       0.00      0.00      0.00         1
          66       0.00      0.00      0.00         5
          68       0.00      0.00      0.00        11
          70   

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [71]:
#calculate the accuracy using the confusion matrix as follows :

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
print("\nAccuracy Of SVM For The Given Dataset : ", accuracy)


Accuracy Of SVM For The Given Dataset :  0.05194805194805195


In [72]:
#Visualizing the classifier
#Before we visualize we might need to encode
#the classes ‘sex’ and ‘chol’ into numericals.
#We can achieve that using the label encoder.

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y_train = le.fit_transform(Y_train)

In [73]:
#After encoding , fit the encoded data to the SVM

from sklearn.svm import SVC
classifier = SVC(kernel='linear', random_state = 1)
classifier.fit(X_train,Y_train)

SVC(kernel='linear', random_state=1)

In [74]:
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

In [75]:
#visualizing the classifier

plt.figure(figsize = (7,7))
X_set, y_set = X_train, Y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01), np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape), alpha = 0.75, cmap = ListedColormap(('black', 'white')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('blue', 'red'))(i), label = j)
plt.title('seed type Vs area')
plt.xlabel('seed type')
plt.ylabel('area')
plt.legend()
plt.show()

MemoryError: Unable to allocate 259. MiB for an array with shape (20000, 1700) and data type float64

<Figure size 504x504 with 0 Axes>

In [76]:
#visualizing the predictions
plt.figure(figsize = (7,7))
X_set, y_set = X_test, Y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),alpha = 0.75, cmap = ListedColormap(('black', 'white')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],c = ListedColormap(('blue', 'red'))(i), label = j)
plt.title('seed type Vs area')
plt.xlabel('seed type')
plt.ylabel('area')
plt.legend()
plt.show()

MemoryError: Unable to allocate 291. MiB for an array with shape (20100, 1900) and data type float64

<Figure size 504x504 with 0 Axes>